### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by peaveyman** [boranblok/nntpPoster#1]
I would like to try this out but I don't see a read me file or instructions on how to use it.

**Comment by boranblok** [comment]
A Decent readme and installation guide is on my todo list. Expect to get a 0.2 release within the next few days that includes these.

**Comment by peaveyman** [comment]
That's great. Looking forward to trying it out. Will it post a directory using the directory name as the subject?

**Comment by boranblok** [comment]
Yes, all directory contents are zipped and it will post using the directory name or an obfuscated name (guid) if obfuscation is enabled.

**Comment by peaveyman** [comment]
Can the zipping be disabled? I do music and would rather they not be zipped. I have a script that does the pars for me and renames the folder to my preferred naming scheme. Whichever uploader I use is called at the end of the script.

**Comment by boranblok** [comment]
hmmh, That would be a feture request then. Right now the rar & par is not designed to be disabled. but it could probably be done without too much effort.

**Comment by peaveyman** [comment]
If the rar & par & zip can be disabled and the it will upload using the directory name as the subject that would be great. I need a specific naming scheme and my script does that along with the pars. This is how my header with the subject line needs to look:

Montgomery_Gentry-My_Town-Flac-2002 [12/27] - "My Town - 01 - My Town (Piano Intro).flac" yEnc (1/3)

Also, will it upload the files in sequential order and is there a header check function? 

The reason I'm asking is I just found your app and am wanting to use something that is currently being developed and just want to know what it's capable of.

**Comment by boranblok** [comment]
Hmmh, modifying the header to conform to that specific format might be beyond my scope. I think currently it is rather close to that format now however. Might be slightly different.

File order in an upload is not guaranteed to be honest.

If you want these specific alterations you are definitely free to fork it. These are no big changes, but feel to me like they deviate too much from my intended scope.

**Comment by peaveyman** [comment]
Ok, thank you.
