### ISSUE TITLE
[Feature Request] Add Date and Time

### ISSUE THREAD

**Issue by unixjeff** [boranblok/nntpPoster#13]
On the Terminal it shows "xxxx/xxxx uploaded at 15.90MB/s" can the date and time be added so when looking at it you can tell when the last one took place?

xxxx/xxxx uploaded at 15.90MB/s on 10/10/2016 10:10:10

**Comment by stephenl03** [comment]
Pretty sure this issue can be closed out. Every log entry has a timestamp
```
2017-03-15 05:22:42,110 INFO 6 nntpAutoposter.AutoPoster - [FILE.NAME.HERE] was uploaded as obfuscated release [07e81e1ec5679571d2baad75c44c8c51] to usenet.
```

**Comment by boranblok** [comment]
Yeah, I will close this. The console really isnt the main target of support, for all detailed info the log file is the place to be. detailed logs can be extracted by using more advanced log4net filters and notifiers. I could incluse some samples of filters like that if it would be helpful.
