### ISSUE TITLE
[Feature Request] Remove MKV's UniqueID While Striping File Metadata

### ISSUE THREAD

**Issue by judhat2** [boranblok/nntpPoster#18]
If StripFileMetadata is set to true, it looks like mkvpropedit only removes the title from the metadata.  Can it also remove the Unique ID of .mkv files? The command is `mkvpropedit --delete segment-uid file.mkv`.

The MKV Unique ID is changed when ffmpeg removes all the metadata and creates a new mkv, obviously. However, the problem is that the language ID of the video audio and any embedded subtitles are removed when ffmpeg does that.  Right now, I am just telling nntpPoster a false location of ffmpeg so it doesn't run that command.  Maybe set a separate option in the config for each ffmpeg and mkvpropedit, instead of allowing `StripFileMetadata=yes` to run both?

I think removing the MKV Unique ID will help with the obfuscation.

**Comment by boranblok** [comment]
I am probably going to remove the ability to strip metadata alltogether. 

Modifying source files makes it harder to reshare files back etc.

If this functionality is still required I suggest adding a shell script in between folders that strip this metadata before moving it to the watch folder.

**Comment by judhat2** [comment]
Since this post, I've set up a script to remove the mkv id before uploading which is working well.  However, it might be worth a 2nd thought to implement it.  I am pretty sure that nZEDb and newznab have an option to deobfuscate posts via their mkv unique id. Removing it could help keep those posts from being identified.
 
I understand that it changes the file, and I assume you mean it makes it harder sharing the file back via torrents.  If someone wanted to share an mkv via its original torrent, they could "fix" the mkv by downloaded the missing bytes from a peer.  It would only be a problem if there were no more peers to get the missing information from.

But as I said, my script is working fine for me. I understand if you still don't want to allow the metadata to be modified, as it is your project. :)

**Comment by ehsope** [comment]
What's the point of doing this?
