### ISSUE TITLE
[Feature Request] Alter target group based on watched folder

### ISSUE THREAD

**Issue by Darkknight33** [boranblok/nntpPoster#19]
Not everything posted to usenet should end up in a single group. If there were subfolders under the watch folder with the group name, that could be used as the target group for posting instead of a single preset group.

E.g.

nntpautoposter
|__ watch
 __|_iso
__|_boneless
__|_multimedia

Note that it would take additional logic to post to multiple groups using this method, but if required, the folder names could serve as category labels instead and the groups then defined on a per category basis within the config.

**Comment by boranblok** [comment]
You can already get a structure like this by making multiple watchfolder configurations and simply modifying the target news group per watchfolder configuration.

So config1:
```
[Watchfolder]
ShortName=amazing

[..]
TargetNewsgroups=alt.binaries.amazing
[..]
```

config2

```
[Watchfolder]
ShortName=ath

[..]
TargetNewsgroups=alt.binaries.ath
[..]
```
