### ISSUE TITLE
<RemoveAfterVerify>

### ISSUE THREAD

**Issue by Rockybb** [boranblok/nntpPoster#22]
how to use <RemoveAfterVerify> true/false, in the new versions?

**Comment by boranblok** [comment]
https://github.com/boranblok/nntpPoster/wiki/Advanced-Configuration#boolean-values

but you are referring an xml tag. those are not used anymore. Configuration is now done with .ini files.

**Comment by Rockybb** [comment]
But right now if I use the latest version, the poster will delete my upload after checking if it is complete.
But I would like to keep the upload in the backup folder..
Can I get the program to do it? :)

**Comment by boranblok** [comment]
Can you post the relevant section of the configuration where you set that value to false/no/NO ?

Do note that this setting is also stored together with the upload. So after changing it will only apply to items you put in the watch folder after you have changed this.

Also not that when you disable remove after verify you need a way to clean out the backup folder yourself. while keeping into account not to delete files that are pending verification.

**Comment by Rockybb** [comment]
I have make a clean install before changing setting,.... 

back to version 0.7.2. I could choose the program not clear my backup folder.
Would be nice if possible again.! :)
So if I set "VerificationType" to "dummy"... I like the program not to cleaning my backup folder. 
is it possible? 

hope you understand what I mean and sorry for my bad english!!!!!! :)

**Comment by boranblok** [comment]
Rocky,

I would still like some sample parts of where you set the config. Because the method of configuration changed a few times (now it is ini files)

**Comment by Rockybb** [comment]
Here is my config files. in the userconf folder:

config file:
ApiKey=APIKEY
NotificationType=NewznabHash
ObfuscatedNotificationUrl=https://api.apiserver.com/api?hash={0}&name={1}&apikey=${ApiKey}
VerificationType=Dummy
SearchUrl=https://api.apiserver.com/api?t=search&q={0}&maxage={1}&apikey=${ApiKey}
Working=working
NzbOutput=NZB
Backup=backup
PostFailed=uploadfailed
MaxRepostCount=3
RarNParSettings=0,15,10|1024,50,10|5120,100,10
InactiveProcessTimeoutMinutes=10

in my watchfolder.ini
ShortName=default
Path=watch
UseObfuscation=yes
CleanName=no

**Comment by boranblok** [comment]
in your use configuration ini:

    [Posting]
    # When a release has been found on the indexer, remove it from the backup location or not.
    # It is best to leave this on unless you have a manual cleaning process.
    RemoveAfterVerify=yes

(f the `[posting]` header is already present (most likely the case)  you dont have to re-add it)
