### ISSUE TITLE
 [Feature Request] simple ftp upload of nzb after it has posted (alternative to notify)

### ISSUE THREAD

**Issue by jaykae89** [boranblok/nntpPoster#23]
a ftp option would be great to upload the nzb to a server after it has finished uploading 

allowing users to use a modified import script to do things with the nzb file e.g dupe checker ect

**Comment by boranblok** [comment]
FTP upload is far outside of the scope of this project. I suggest using a separate application that watches the nzb folder and uploads to FTP.
