### ISSUE TITLE
Running on crontab

### ISSUE THREAD

**Issue by bezzkos** [boranblok/nntpPoster#24]
Hello.
I'm on remote server now with no sudo rights and try making nntpPoster autoloading on startup. But only one choice i'm have is crontab. ITs possible with this software? Sorry on my eng :(

**Comment by boranblok** [comment]
You can periodically run the [`start.sh`](https://github.com/boranblok/nntpPoster/blob/master/nntpAutoposter/start.sh) file. This runs the application in a screen session, and (re)starts the application if the screen session is missing.
