### ISSUE TITLE
How does NZBPost work?

### ISSUE THREAD

**Issue by Fossil01** [boranblok/nntpPoster#27]
Can't seem to get `NotificationType=NzbPost`

What does the `ObfuscatedNotificationUrl` need to look like and what kind of output is expected?

Also, could there be support for multiple ObfuscatedNotificationUrl's?

**Comment by Fossil01** [comment]
@boranblok Any idea?

**Comment by judhat2** [comment]
Go to https://nzbgeek.info/showthread.php?tid=5454&pid=33854#pid33854 to see an example of the nzbpost config.
