### ISSUE TITLE
Fix Docs

### ISSUE THREAD

**Issue by methanoid** [boranblok/nntpPoster#43]
They aren't good... eg. How do you specify Obfuscated or Non-Ob? How do you specify poster name/email address or does it just leave them blank? Where do you choose the binaries group....  Obviously author knows how but his s/w needs proper docs

**Comment by boranblok** [comment]
https://github.com/boranblok/nntpPoster/wiki

Feel free to provide suggestions how I can improve this, but all points you mention are explained there.

**Comment by methanoid** [comment]
If only you were as responsive to feedback as you were to closing the issue :-(  

I did read the "docs". They are NOT there (the answers). The order of the docs is (quite honestly) bonkers. Advanced Config comes first? No... should be Installation(s), Then Config, Then Advanced.. then maybe "how to use"????  I have no doubt this is good software but I cannot use it if the docs are no help. Sorry, I know you don't want to hear anything negative but it's how a potential user feels 👎

**Comment by boranblok** [comment]
I dont really have much influence it seems on that order, as it seems to be in alphabetical order.

I would suggest you start with the installation part on your OS, and then read the config and watchfolder config.

advanced config can be omitted entirely as this is not required.

I have to agree with you that the application is not very user friendly, and this is a point to work on. Sadly this is a side project and I cannot spend time on this at the moment.

I do mean that all points you asked are answered in the docs. Obfuscated/Non, Postername/email (=FromAddress) and usernet groups are all configured in the [watchfolder config](https://github.com/boranblok/nntpPoster/wiki/Watchfolder-Configuration).

**Comment by methanoid** [comment]
Thanks. Now, I had no idea I needed to read Watchfolder config as I didnt plan to automate that side. I assumed (in absence of info to contrary) that I could tell it what I wanted to upload...  I'll go read that bit then!  ;-)

**Comment by boranblok** [comment]
One point that might not be clear is the goal of this application.

This application is mainly used to automate usenet uploads. The output of an automated grabbing process (be it torrents, usenet, XDCC, whatever) is copied/moved over to a watchfolder and this then causes a (re)upload to usenet.

It can also be used as something that just runs like sabnzbd but in reverse. You manually files into a folder and voila, they go to usenet.

If this is not your use case forcing the application to your use case will cause some friction. The application is also intended to run as a service, so it is not something one would use to upload a single file to usenet once.

Underneath it does have an application that uploads one single file, but support for that has withered a bit. As there are many other tools that are far better at this role. Taking a good look at that single file uploader is on my todo list.
