### ISSUE TITLE
Request for rar password

### ISSUE THREAD

**Issue by jonnyboy** [boranblok/nntpPoster#5]
Is it possible to add passwords to the rar process?

Thank you

**Comment by boranblok** [comment]
It is possible, and probably not that hard to do. However this would preclude the notification process to the indexer from working properly. So you'dhave to definitly enable the nzb output and upload that.

I dont have time to develop for a while, but It will probably be done by next weekend.

**Comment by jonnyboy** [comment]
That would be great.

Thank you

**Comment by boranblok** [comment]
Version 0.6.0 just released. This version added this feature.

Please let me know if you have any issues with it.

**Comment by jonnyboy** [comment]
thank you. I look forward to testing this this weekend.
