### ISSUE TITLE
Place .NZB file and .NFO file next to the upload

### ISSUE THREAD

**Issue by LoveLace55** [boranblok/nntpPoster#52]
Hello, the newbie is back with a new question.

Is it possible to add a seperate NZB file and NFO file that are not compressed but uploaded along the files so that the indexers display it ?

thanks

**Comment by boranblok** [comment]
uploading an nzb itself is kind of pointless, as the nzb is a reference to the usenet files, this would be somewhat recursive.

if you generate an nfo yourself, you can place it and a file in a folder, however be aware the filename itself will not be obfuscated, an nzb can only carry one piece of information.

**Comment by LoveLace55** [comment]
Ok, but how do i make the .nfo file uploaded along all the other rar files and not zipped inside the archives ? I want the nfo file to be of the same name as the folder

**Comment by boranblok** [comment]
I don't really see what you're trying to achieve, do you want an nzb with a single link to an nfo file, and then the rars?

**Comment by LoveLace55** [comment]
What I would like is that the poster RAR all the files, then add an outside NFO file along with them, and upload them all. So that when you see the post in the indexer, you can check the nfo file to see what it is all about

**Comment by boranblok** [comment]
I see, right now this is not really possible, I'd have to see if I can add logic to specifically deal with .nfo files and add an exception to those or something.

Generating the .nfo is left to an external application I presume, you will place abc.mkv and abc.nfo in the watch folder then ?

**Comment by LoveLace55** [comment]
Well, I like to write some text in the nfo file describing what is inside the rar files. The way I see it, Nttpposter looks for the watch folder, IF it has an .nfo file that is the exact name as the watch folder, IT copies it to the send folder, THEN proceeds by raring and paring the folder, THEN copies the rar files to the send folder wher the info file is, then send the hole batch with rar files and nfo to usenet.

**Comment by boranblok** [comment]
yeah, I see the use case and method how it would work, so I'll implement it if I have some time.

**Comment by LoveLace55** [comment]
Great ! Thanks !

**Comment by boranblok** [comment]
Version 0.12.0 I just released adds new logic that if a file or folder has an accompanying .nfo file this file is not rarred or parred but instead put next to the rars and pars in the upload and .nzb.

Be aware that an nfo containing descriptive info kind of defeats the whole point of obfuscation so you might not want to bother obfuscating either in this scenario.

**Comment by ddivita** [comment]
Maybe an email with the obfuscated info might be better than an nfo file.
