### ISSUE TITLE
Windows Installation Instructions Wiki Links to Old par2cmdline-0.4

### ISSUE THREAD

**Issue by didamsko** [boranblok/nntpPoster#62]
New to nntpPoster and after following the Windows installation instructions: 

https://github.com/boranblok/nntpPoster/wiki/Installation-on-Windows

I ran into memory issues when trying to par bigger files. It took me a while figure out what was going wrong and to find this newer fork: https://github.com/Parchive/par2cmdline/ that does the job properly. But i now see that the newer fork is already linked under the prerequisites: 

https://github.com/boranblok/nntpPoster

Just not on the Windows installation instructions page. So best update the Windows installation with a link to the new fork. The older par2cmdline-0.4 did work for smaller files but on my system just could not handle parring big files resulting in nntpPoster failing.

**Comment by boranblok** [comment]
Modified the link.
