### ISSUE TITLE
PreTag

### ISSUE THREAD

**Issue by jonnyboy** [boranblok/nntpPoster#8]
You have an option for PostTag, could you add a PreTag

<PreTag></PreTag>

I presume this would prefix the the PreTag to the filename for the upload name.

**Comment by jonnyboy** [comment]
Are you on irc anywhere? I would like the opportunity to speak with you. Might be easier than on here.

**Comment by jonnyboy** [comment]
I am trying to add some command line options. If you have the time, could me meet up in irc or on skype. Anywhere that is convenient for you.

Thanks

**Comment by boranblok** [comment]
PreTag has been added. But not in a release version yet.

I am not very available on irc or skype, got lots of irl stuff to take care of as well.
